#!/bin/bash

echo "🔍 Checking OpenAI API Usage and Rate Limits..."
echo ""

echo "To check your OpenAI account:"
echo "1. Go to: https://platform.openai.com/account/limits"
echo "2. Check your tier and rate limits"
echo ""
echo "Current recommended models:"
echo "  ✅ Chat: gpt-4o-mini (latest, affordable)"
echo "  ✅ Embeddings: text-embedding-3-small (cheapest)"
echo ""
echo "For a 1MB PDF:"
echo "  - Expected chunks: 50-100"
echo "  - Embedding API calls: 50-100"
echo "  - Cost: ~\$0.001-0.002"
echo ""
echo "If you're on free tier:"
echo "  - Rate limit: 3 requests/minute"
echo "  - 1MB PDF = 50-100 calls = 17-33 minutes to process"
echo "  - Solution: Upgrade to paid tier or add delays"
